# --- Base role defaults ---
base_timezone: "Europe/Berlin"
base_locale: "en_US.UTF-8"
base_ntp_servers: "0pool.ntp.org 1pool.ntp.org 2.pool.ntp.org"

ssh_port: 22
ssh_allow_cidrs:
 - "192.0.2.10/16"
 - "192.0.2.10/8"
 - "192.0.2.10/12"

base_forward_cidr: "192.0.2.10/24"
base_forward_ports: [8080, 8096]

# Optional lists
base_groups: []
base_dirs: []
