---
- Name: <REDACTED>
 hosts: local-node
 become: true
 gather_facts: false
 vars:
 paper_container: "paper"
 tasks:
 - community.docker.docker_container:
 Name: <REDACTED>
 state: stopped
 force_kill: true
